create table stores (
	id INT,
	city VARCHAR(50),
	home_store VARCHAR(50)
);
insert into stores (id, city, home_store) values (1, 'Sandouping', 'Kihn, Goldner and Dare');
insert into stores (id, city, home_store) values (2, 'Huilong', 'McDermott LLC');
insert into stores (id, city, home_store) values (3, 'Pemberton', 'Miller Inc');
insert into stores (id, city, home_store) values (4, 'Hamar', 'Cartwright, Beier and Von');
insert into stores (id, city, home_store) values (5, 'Wenceslao Escalante', 'Jerde-Wolf');
insert into stores (id, city, home_store) values (6, 'Farmington', 'Leannon Group');
insert into stores (id, city, home_store) values (7, 'Gunungkencana', 'Kassulke LLC');
insert into stores (id, city, home_store) values (8, 'Macapsing', 'Dare-Emmerich');
insert into stores (id, city, home_store) values (9, 'Osięciny', 'Padberg, Lynch and Eichmann');
insert into stores (id, city, home_store) values (10, 'Alurbulu', 'Gorczany, Schulist and Reinger');
insert into stores (id, city, home_store) values (11, 'Poctol', 'Kuphal, Murazik and Reinger');
insert into stores (id, city, home_store) values (12, 'Kalianget', 'Marquardt, Walter and Pfeffer');
insert into stores (id, city, home_store) values (13, 'Cañaveral', 'Hackett Inc');
insert into stores (id, city, home_store) values (14, 'Luoxiong', 'Murazik-Nitzsche');
insert into stores (id, city, home_store) values (15, 'Rostock', 'Osinski, Steuber and DuBuque');
insert into stores (id, city, home_store) values (16, 'Sagay', 'Berge Group');
insert into stores (id, city, home_store) values (17, 'Zhuangta', 'Brown Group');
insert into stores (id, city, home_store) values (18, 'Urungpigang', 'Russel-Crona');
insert into stores (id, city, home_store) values (19, 'Gwangtan', 'Schimmel Inc');
insert into stores (id, city, home_store) values (20, 'Changle', 'Stokes, Abshire and Kerluke');
insert into stores (id, city, home_store) values (21, 'Lorino', 'Hudson Inc');
insert into stores (id, city, home_store) values (22, 'Christiana', 'Kiehn LLC');
insert into stores (id, city, home_store) values (23, 'Stupsk', 'Treutel, Collins and Morissette');
insert into stores (id, city, home_store) values (24, 'Ombarade', 'Okuneva Group');
insert into stores (id, city, home_store) values (25, 'Alto del Espino', 'Herzog-Senger');
insert into stores (id, city, home_store) values (26, 'Renhe', 'Schroeder-Lesch');
insert into stores (id, city, home_store) values (27, 'Armenia', 'Gaylord LLC');
insert into stores (id, city, home_store) values (28, 'Songmuping', 'Bruen, Cummings and Eichmann');
insert into stores (id, city, home_store) values (29, 'Sumberarumkrajan', 'Buckridge Group');
insert into stores (id, city, home_store) values (30, 'Vrbno pod Pradědem', 'Lind and Sons');
insert into stores (id, city, home_store) values (31, 'Coelho Neto', 'Crooks, Wiza and Friesen');
insert into stores (id, city, home_store) values (32, 'Karangparwa', 'Hegmann, Turner and Brekke');
insert into stores (id, city, home_store) values (33, 'Aipe', 'Homenick-Huels');
insert into stores (id, city, home_store) values (34, 'Zhuxi Chengguanzhen', 'Hudson-Goldner');
insert into stores (id, city, home_store) values (35, 'Fort Worth', 'Schmeler and Sons');
insert into stores (id, city, home_store) values (36, 'Umeå', 'Rogahn, Bashirian and Frami');
insert into stores (id, city, home_store) values (37, 'Shuiche', 'Kilback-Goyette');
insert into stores (id, city, home_store) values (38, 'San Luis', 'Beier Inc');
insert into stores (id, city, home_store) values (39, 'Baru Timur', 'Corwin, Rippin and Dickens');
insert into stores (id, city, home_store) values (40, 'Palguyod', 'Bahringer, Littel and Romaguera');
insert into stores (id, city, home_store) values (41, 'Jayapura', 'Romaguera, Gaylord and Murphy');
insert into stores (id, city, home_store) values (42, 'Lobito', 'Fritsch LLC');
insert into stores (id, city, home_store) values (43, 'Galatás', 'Buckridge, Aufderhar and Dooley');
insert into stores (id, city, home_store) values (44, 'Wa', 'Okuneva-Williamson');
insert into stores (id, city, home_store) values (45, 'Imbituba', 'Pollich Group');
insert into stores (id, city, home_store) values (46, 'Zarrīn Shahr', 'Konopelski Inc');
insert into stores (id, city, home_store) values (47, 'Gllogjan', 'Shields-Frami');
insert into stores (id, city, home_store) values (48, 'Noyelles-sous-Lens', 'Hahn Group');
insert into stores (id, city, home_store) values (49, 'Ulset', 'Mohr-Block');
insert into stores (id, city, home_store) values (50, 'Tía Juana', 'Robel, Block and Keeling');
insert into stores (id, city, home_store) values (51, 'Gongnong', 'Kuhlman, Dibbert and Brekke');
insert into stores (id, city, home_store) values (52, 'Kefar Shemaryahu', 'McLaughlin-Bosco');
insert into stores (id, city, home_store) values (53, 'Parigi', 'Jacobi, Gislason and Sporer');
insert into stores (id, city, home_store) values (54, 'Tugu', 'Wilkinson Group');
insert into stores (id, city, home_store) values (55, 'Sungaikakap', 'Weimann-Moore');
insert into stores (id, city, home_store) values (56, 'Njeru', 'Haag Group');
insert into stores (id, city, home_store) values (57, 'Padina', 'McCullough and Sons');
insert into stores (id, city, home_store) values (58, 'Kirkland Lake', 'Johnson, Dibbert and Yost');
insert into stores (id, city, home_store) values (59, 'Shangzhang', 'Hagenes and Sons');
insert into stores (id, city, home_store) values (60, 'Chahe', 'Douglas-Ankunding');
insert into stores (id, city, home_store) values (61, 'Loma Bonita', 'Christiansen Group');
insert into stores (id, city, home_store) values (62, 'Dos Hermanas', 'Hoeger, Zulauf and Satterfield');
insert into stores (id, city, home_store) values (63, 'Cipesing', 'Hegmann Inc');
insert into stores (id, city, home_store) values (64, 'Liren', 'Harber LLC');
insert into stores (id, city, home_store) values (65, 'Rungkam', 'Treutel, Hayes and Ryan');
insert into stores (id, city, home_store) values (66, 'Banga', 'Abernathy-Sporer');
insert into stores (id, city, home_store) values (67, 'Taraš', 'Hyatt-Swift');
insert into stores (id, city, home_store) values (68, 'Dibulla', 'Gleichner-Bergnaum');
insert into stores (id, city, home_store) values (69, 'Macun', 'Orn, Okuneva and Quitzon');
insert into stores (id, city, home_store) values (70, 'San Marcos', 'Heaney, Balistreri and Lynch');
insert into stores (id, city, home_store) values (71, 'Longmen', 'Streich Group');
insert into stores (id, city, home_store) values (72, 'Lue Amnat', 'Cruickshank Inc');
insert into stores (id, city, home_store) values (73, 'Longchi', 'Davis LLC');
insert into stores (id, city, home_store) values (74, 'General Emilio Aguinaldo', 'Gleason-Deckow');
insert into stores (id, city, home_store) values (75, 'Guápiles', 'Spinka Group');
insert into stores (id, city, home_store) values (76, 'Nastola', 'Nicolas-Gulgowski');
insert into stores (id, city, home_store) values (77, 'Bayḩān', 'Rempel, Bayer and West');
insert into stores (id, city, home_store) values (78, 'Shigu', 'Nienow Inc');
insert into stores (id, city, home_store) values (79, 'Xirikxiy', 'Breitenberg, Bogisich and Boyer');
insert into stores (id, city, home_store) values (80, 'Lage', 'Batz, Hodkiewicz and Keebler');
insert into stores (id, city, home_store) values (81, 'Klos', 'Ratke-Ankunding');
insert into stores (id, city, home_store) values (82, 'Düsseldorf', 'Smith and Sons');
insert into stores (id, city, home_store) values (83, 'Nanhuang', 'Huel-Mills');
insert into stores (id, city, home_store) values (84, 'Kissimmee', 'O''Connell-Gleichner');
insert into stores (id, city, home_store) values (85, 'Sumberbaru', 'Metz, Brakus and Schinner');
insert into stores (id, city, home_store) values (86, 'Dabat', 'Wilkinson, Streich and Hane');
insert into stores (id, city, home_store) values (87, 'Ricardo Flores Magon', 'Gutmann Inc');
insert into stores (id, city, home_store) values (88, 'Mainit', 'Franecki-Leannon');
insert into stores (id, city, home_store) values (89, 'Xinle', 'Metz, Hauck and Hammes');
insert into stores (id, city, home_store) values (90, 'Monteros', 'Jakubowski Group');
insert into stores (id, city, home_store) values (91, 'Banī Ḩassān', 'Cronin Group');
insert into stores (id, city, home_store) values (92, 'Syevyerodonets’k', 'Christiansen, Rippin and Goldner');
insert into stores (id, city, home_store) values (93, 'Poddębice', 'Dickens-Mitchell');
insert into stores (id, city, home_store) values (94, 'Hualongyan', 'Kessler-Tromp');
insert into stores (id, city, home_store) values (95, 'Delanggu', 'Hahn, Tremblay and Murazik');
insert into stores (id, city, home_store) values (96, 'Bogoroditsk', 'Kreiger-Runte');
insert into stores (id, city, home_store) values (97, 'Zhongcun', 'Kuhic, Walsh and Shanahan');
insert into stores (id, city, home_store) values (98, 'Peruc', 'Trantow LLC');
insert into stores (id, city, home_store) values (99, 'Paraíso', 'Langosh-Friesen');
insert into stores (id, city, home_store) values (100, 'Midland', 'Fadel Group');
